on:
  push:
    branches:
      - main
  pull_request:

jobs:
  spell_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt -y install aspell
      - run: ./spellcheck.sh

  run_commands:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: python3 run_commands.py
      - run: git diff --exit-code
