on:
  push:
    branches:
      - master
  pull_request:

jobs:
  spell_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt -y install aspell
      - run: ./spellcheck.sh

  run_commands:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: hostname
      - run: |
          python3 run_commands.py
          git diff --exit-code
