on:
  push:
    branches:
      - main
  pull_request:

jobs:
  spell_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt -y install aspell
      - run: ./spellcheck.sh

  build:
    strategy:
      matrix:
        # TODO: macos build gets stuck somehow
        #os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        os: ["ubuntu-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install -r requirements.txt
      - run: python3 build.py
      - uses: actions/upload-artifact@v2
        with:
          name: build-${{ matrix.os }}
          path: build

  linkchecker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: build-ubuntu-latest
          path: build
      - uses: actions/setup-python@v2
      - run: pip install git+https://github.com/linkchecker/linkchecker.git
      - name: Run linkchecker
        run: |
          # https://github.com/linkchecker/linkchecker/issues/542
          for file in build/*.html; do
            linkchecker --config=./linkcheckerrc $file
          done
