on:
  push:
    branches:
      - main
  pull_request:

jobs:
  spell_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt -y install aspell
      - run: ./spellcheck.sh

  build_and_linkchecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install -r requirements.txt
      - run: python3 build.py
      - run: pip install git+https://github.com/linkchecker/linkchecker.git
      - run: linkchecker build/*.html
